#!/usr/bin/env sh

# Synopsis:
# Test the test runner Docker image by running it against a predefined set of 
# solutions with an expected output.
# The test runner Docker image is built automatically.

# Output:
# Outputs the diff of the expected test results against the actual test results
# generated by the test runner Docker image.

# Example:
# ./test.sh

# Build the Docker image
docker build --rm -t exercism/clojure-test-runner /home/runner/work/clojure/clojure/clojure-test-runner/

# Run the Docker image using the settings mimicking the production environment
# TODO: --read-only
docker run \
    --rm \
    --network none \
    --mount type=bind,src=/home/runner/work/clojure/clojure/main/exercises/,dst=/home/runner/work/clojure/clojure/clojure-test-runner/ \
    --mount type=tmpfs,dst=/tmp \
    --workdir /home/runner/work/clojure/clojure/main/ \
    --entrypoint /home/runner/work/clojure/clojure/main/test.clj \
    exercism/clojure-test-runner